// Copyright 2025 - 2026 The excelize Authors. All rights reserved. Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.
//
// Package excelize-cs is a C# port of Go Excelize library, providing a set of
// functions that allow you to write and read from XLAM / XLSM / XLSX / XLTM /
// XLTX files. Supports reading and writing spreadsheet documents generated by
// Microsoft Excel™ 2007 and later. Supports complex components by high
// compatibility, and provided streaming API for generating or reading data from
// a worksheet with huge amounts of data. This library needs .NET version 6, C#
// version 10 or later.

namespace ExcelizeCs.Tests;

using System.Runtime.InteropServices;
using Xunit;

public class UnitTest
{
    [Fact]
    public void TestAddChart()
    {
        File f = Excelize.NewFile();
        List<List<object?>> data = new List<List<object?>>
        {
            new() { null, "Apple", "Orange", "Pear" },
            new() { "Small", 2, 3, 3 },
            new() { "Normal", 5, 2, 4 },
            new() { "Large", 6, 7, 8 },
        };
        Assert.Null(Record.Exception(() => f.SetSheetRow("Sheet1", "A1", null)));
        Assert.Null(Record.Exception(() => f.SetSheetRow("Sheet1", "A1", new List<object>())));
        foreach (List<object?> row in data)
        {
            Assert.Null(
                Record.Exception(() =>
                    f.SetSheetRow(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, data.IndexOf(row) + 1),
                        row
                    )
                )
            );
        }
        Chart chart = new Chart
        {
            Type = ChartType.Col3DClustered,
            Series = new ChartSeries[]
            {
                new()
                {
                    Name = "Sheet1!$A$2",
                    Categories = "Sheet1!$B$1:$D$1",
                    Values = "Sheet1!$B$2:$D$2",
                },
                new()
                {
                    Name = "Sheet1!$A$3",
                    Categories = "Sheet1!$B$1:$D$1",
                    Values = "Sheet1!$B$3:$D$3",
                },
                new()
                {
                    Name = "Sheet1!$A$4",
                    Categories = "Sheet1!$B$1:$D$1",
                    Values = "Sheet1!$B$4:$D$4",
                },
            },
            Title = new RichTextRun[] { new() { Text = "Fruit 3D Clustered Column Chart" } },
        };
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddChart("Sheet1", "E1", chart);
                f.AddChart("Sheet1", "E16", chart, chart);
                f.AddChart("Sheet1", "E31", chart, null);
                f.AddChart("Sheet1", "E46", chart, Array.Empty<Chart>());
                f.AddChartSheet("Sheet2", chart);
                f.AddChartSheet("Sheet3", chart, chart);
                f.AddChartSheet("Sheet4", chart, null);
                f.AddChartSheet("Sheet5", chart, Array.Empty<Chart>());
                f.DeleteChart("Sheet1", "E46");
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.DeleteChart("SheetN", "A1"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddChart.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddComment()
    {
        File f = Excelize.NewFile();
        Comment comment = new Comment
        {
            Cell = "A5",
            Author = "Excelize",
            Paragraph = new RichTextRun[]
            {
                new()
                {
                    Text = "Excelize: ",
                    Font = new Font { Bold = true },
                },
                new() { Text = "This is a comment." },
            },
            Height = 40,
            Width = 180,
        };
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.DeleteComment("SheetN", "A1"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddComment("Sheet1", null);
                f.AddComment("Sheet1", comment);
                f.DeleteComment("Sheet1", "A5");
                f.SaveAs("TestComment.xlsx");
            })
        );
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddFormControl()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "A3",
                        Macro = "Button1_Click",
                        Width = 140,
                        Height = 60,
                        Text = "Button 1\r\n",
                        Paragraph = new RichTextRun[]
                        {
                            new()
                            {
                                Font = new Font
                                {
                                    Bold = true,
                                    Italic = true,
                                    Underline = "single",
                                    Family = "Times New Roman",
                                    Size = 14,
                                    Color = "777777",
                                },
                                Text = "C1=A1+B1",
                            },
                        },
                        Type = FormControlType.FormControlButton,
                        Format = new GraphicOptions
                        {
                            PrintObject = true,
                            Positioning = "absolute",
                        },
                    }
                );
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "A1",
                        Macro = "Button1_Click",
                        Text = "Option Button 1",
                        Type = FormControlType.FormControlOptionButton,
                    }
                );
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "B1",
                        Type = FormControlType.FormControlSpinButton,
                        Width = 15,
                        Height = 40,
                        CurrentVal = 7,
                        MinVal = 5,
                        MaxVal = 10,
                        IncChange = 1,
                        CellLink = "A1",
                    }
                );
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "B3",
                        Type = FormControlType.FormControlScrollBar,
                        Width = 140,
                        Height = 20,
                        CurrentVal = 50,
                        MinVal = 10,
                        MaxVal = 100,
                        PageChange = 1,
                        CellLink = "A1",
                        Horizontally = true,
                    }
                );
                f.SetSheetProps("Sheet1", new SheetPropsOptions { CodeName = "Sheet1" });
                f.AddFormControl("Sheet1", null);
                f.AddVBAProject(
                    System.IO.File.ReadAllBytes(
                        Path.GetFullPath(Path.Combine("..", "..", "..", "vbaProject.bin"))
                    )
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddFormControl("SheetN", new FormControl { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.SetSheetProps("SheetN", new SheetPropsOptions { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddFormControl.xlsm")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddIgnoredErrors()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetCellValue("Sheet1", "A3", "3");
                int row = 1;
                foreach (IgnoredErrorsType errorType in Enum.GetValues(typeof(IgnoredErrorsType)))
                {
                    f.AddIgnoredErrors(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, row++),
                        errorType
                    );
                }
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddIgnoredErrors("SheetN", "A1", IgnoredErrorsType.IgnoredErrorsEvalError)
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddIgnoredErrors.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddPicture()
    {
        File f = Excelize.NewFile();
        string filePath = Path.GetFullPath(Path.Combine("..", "..", "..", "..", "chart.png"));
        byte[] pic = System.IO.File.ReadAllBytes(filePath);
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddPicture("Sheet1", "A1", filePath, null);
                f.AddPicture(
                    "Sheet1",
                    "A1",
                    filePath,
                    new GraphicOptions
                    {
                        PrintObject = true,
                        ScaleX = 0.1,
                        ScaleY = 0.1,
                        Locked = false,
                    }
                );
                f.AddPictureFromBytes(
                    "Sheet1",
                    "A3",
                    new Picture
                    {
                        Extension = ".png",
                        File = pic,
                        Format = new GraphicOptions
                        {
                            PrintObject = true,
                            ScaleX = 0.1,
                            ScaleY = 0.1,
                            Locked = false,
                        },
                        InsertType = PictureInsertType.PictureInsertTypePlaceOverCells,
                    }
                );
                f.DeletePicture("Sheet1", "A4");
                f.SaveAs("TestAddPicture.xlsx");
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddPicture("SheetN", "A1", filePath, null)
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DeletePicture("SheetN", "A1"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAppProperties()
    {
        File f = Excelize.NewFile();
        AppProperties props = new AppProperties
        {
            Application = "ExcelizeCs",
            Company = "Excelize",
            AppVersion = "1.0.0",
        };
        Assert.Null(Record.Exception(() => f.SetAppProps(props)));
        Assert.Equal(props, f.GetAppProps());
        Assert.Null(Record.Exception(() => f.SaveAs("TestAppProps.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddShape()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddShape(
                    "Sheet1",
                    new Shape
                    {
                        Cell = "G6",
                        Type = "rect",
                        Line = new ShapeLine { Color = "4286F4", Width = 1.2 },
                        Fill = new Fill { Color = new string[] { "8EB9FF" }, Pattern = 1 },
                        Paragraph = new RichTextRun[]
                        {
                            new()
                            {
                                Text = "Rectangle Shape",
                                Font = new Font
                                {
                                    Bold = true,
                                    Italic = true,
                                    Family = "Times New Roman",
                                    Size = 19,
                                    Color = "777777",
                                    Underline = "sng",
                                },
                            },
                        },
                        Width = 180,
                        Height = 40,
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddShape("SheetN", new Shape { Cell = "G6", Type = "rect" })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddShape.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddSlicer()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.NewSheet("Sheet2");
                f.AddTable("Sheet1", new Table { Name = "Table1", Range = "A1:D5" });
                f.AddTable(
                    "Sheet2",
                    new Table
                    {
                        Range = "F2:H6",
                        Name = "table",
                        StyleName = "TableStyleMedium2",
                        ShowFirstColumn = true,
                        ShowLastColumn = true,
                        ShowRowStripes = false,
                        ShowColumnStripes = true,
                    }
                );
                f.AddSlicer(
                    "Sheet1",
                    new SlicerOptions
                    {
                        Name = "Column1",
                        Cell = "E1",
                        TableSheet = "Sheet1",
                        TableName = "Table1",
                        Caption = "Column1",
                    }
                );
                f.AddSlicer(
                    "Sheet1",
                    new SlicerOptions
                    {
                        Name = "Column1",
                        Cell = "I1",
                        TableSheet = "Sheet2",
                        TableName = "table",
                        Caption = "Column1",
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddSlicer("Sheet1", new SlicerOptions { })
        );
        Assert.Equal("parameter is invalid", err.Message);
        Assert.Null(
            Record.Exception(() =>
            {
                f.DeleteSlicer("Column1");
            })
        );
        err = Assert.Throws<RuntimeError>(() => f.DeleteSlicer("x"));
        Assert.Equal("slicer x does not exist", err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddTable("Sheet1", new Table { }));
        Assert.Equal("parameter is invalid", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddSlicer.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddSparkline()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddSparkline(
                    "Sheet1",
                    new SparklineOptions
                    {
                        Location = new string[] { "A2" },
                        Range = new string[] { "Sheet1!B1:J1" },
                        Markers = true,
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddSparkline("SheetN", new SparklineOptions { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddSparkline.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAutoFilter()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.AutoFilter("Sheet1", "A2:D4", new AutoFilterOptions[] { });
                f.AutoFilter(
                    "Sheet1",
                    "F2:H4",
                    new AutoFilterOptions[]
                    {
                        new AutoFilterOptions { Column = "F", Expression = "x != blanks" },
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AutoFilter("SheetN", "L1:N4", new AutoFilterOptions[] { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAutoFilter.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestCalcCellValue()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetSheetRow("Sheet1", "A1", new List<object> { 1, 2 });
                f.SetCellFormula("Sheet1", "C1", "A1+B1");
                Assert.Equal("3", f.CalcCellValue("Sheet1", "C1"));
                Assert.Equal("A1+B1", f.GetCellFormula("Sheet1", "C1"));
                f.NewSheet("Sheet2");
                f.SetCellFormula("Sheet2", "A3", "{1;2;3}");
                f.NewSheet("Sheet3");
                f.SetCellFormula("Sheet3", "A3", "{\"a\",\"b\",\"c\"}");
                f.NewSheet("Sheet4");
                f.SetCellFormula(
                    "Sheet4",
                    "A3",
                    "{1,2;\"a\",\"b\"}",
                    new FormulaOpts { Ref = "A3:A3", Type = Excelize.STCellFormulaTypeArray }
                );
                f.NewSheet("Sheet5");
                f.SetCellFormula(
                    "Sheet5",
                    "A3",
                    "A1:A2",
                    new FormulaOpts { Ref = "A3:A3", Type = Excelize.STCellFormulaTypeArray }
                );
                f.NewSheet("Sheet6");
                f.SetCellFormula(
                    "Sheet6",
                    "C1",
                    "A1+B1",
                    new FormulaOpts { Ref = "C1:C5", Type = Excelize.STCellFormulaTypeShared }
                );
                f.NewSheet("Sheet7");
                f.SetSheetRow("Sheet7", "A1", new List<object> { "A", "B", "C" });
                f.SetSheetRow("Sheet7", "A2", new List<object> { 1, 2 });
                f.AddTable(
                    "Sheet7",
                    new Table
                    {
                        Range = "A1:C2",
                        Name = "Table1",
                        StyleName = "TableStyleMedium2",
                    }
                );
                f.SetCellFormula(
                    "Sheet7",
                    "C2",
                    "SUM(Table1[[A]:[B]])",
                    new FormulaOpts { Type = Excelize.STCellFormulaTypeDataTable }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.SetCellFormula("SheetN", "C1", "A1+B1")
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        err = Assert.Throws<RuntimeError>(() => f.CalcCellValue("SheetN", "A1"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetCellFormula("SheetN", "A1"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestCalcCellValue.xlsx")));
    }

    [Fact]
    public void TestCalcProps()
    {
        File f = Excelize.NewFile();
        CalcPropsOptions opts = new CalcPropsOptions
        {
            FullCalcOnLoad = true,
            CalcID = 122211,
            ConcurrentManualCount = 5,
            IterateCount = 10,
            ConcurrentCalc = true,
        };
        Assert.Null(Record.Exception(() => f.SetCalcProps(opts)));
        Assert.Equal(opts, f.GetCalcProps());
    }

    [Fact]
    public void TestCoordinates()
    {
        var (col, row) = Excelize.CellNameToCoordinates("Z3");
        Assert.Equal((26, 3), (col, row));
        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.CellNameToCoordinates("A"));
        Assert.Equal(
            "cannot convert cell \"A\" to coordinates: invalid cell name \"A\"",
            err.Message
        );
        Assert.Equal(26, Excelize.ColumnNameToNumber(Excelize.ColumnNumberToName(26)));
        err = Assert.Throws<RuntimeError>(() => Excelize.ColumnNameToNumber("-"));
        Assert.Equal("invalid column name \"-\"", err.Message);
        err = Assert.Throws<RuntimeError>(() => Excelize.ColumnNumberToName(0));
        Assert.Equal(
            "the column number must be greater than or equal to 1 and less than or equal to 16384",
            err.Message
        );
    }

    [Fact]
    public void TestDllImportResolver()
    {
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            Lib.DllImportResolver("lib", null, null)
        );
        Assert.Equal(Lib.ErrUnsupportedPlatformOrArch, err.Message);
    }

    [Fact]
    public void TestHeaderFooter()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetHeaderFooter(
                    "Sheet1",
                    new HeaderFooterOptions
                    {
                        DifferentFirst = true,
                        DifferentOddEven = true,
                        OddHeader = "&R&P",
                        OddFooter = "&C&F",
                        EvenHeader = "&L&P",
                        EvenFooter = "&L&D&R&T",
                        FirstHeader = "&CCenter &\"-,Bold\"Bold&\"-,Regular\"HeaderU+000A&D",
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.SetHeaderFooter("SheetN", new HeaderFooterOptions { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestHeaderFooter.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestHeaderFooterImage()
    {
        File f = Excelize.NewFile();
        string filePath = Path.GetFullPath(Path.Combine("..", "..", "..", "..", "chart.png"));
        byte[] pic = System.IO.File.ReadAllBytes(filePath);
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetCellValue("Sheet1", "A1", "Example");
                f.SetHeaderFooter(
                    "Sheet1",
                    new HeaderFooterOptions
                    {
                        DifferentFirst = true,
                        OddHeader = "&L&GExcelize&C&G&R&G",
                        OddFooter = "&L&GExcelize&C&G&R&G",
                        FirstHeader = "&L&GExcelize&C&G&R&G",
                        FirstFooter = "&L&GExcelize&C&G&R&G",
                    }
                );
                f.AddHeaderFooterImage(
                    "Sheet1",
                    new HeaderFooterImageOptions
                    {
                        Position = HeaderFooterImagePositionType.HeaderFooterImagePositionLeft,
                        File = pic,
                        FirstPage = true,
                        Extension = ".png",
                        Width = "50pt",
                        Height = "32pt",
                    }
                );
                f.AddHeaderFooterImage("Sheet1", null);
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddHeaderFooterImage("SheetN", new HeaderFooterImageOptions { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddHeaderFooterImage.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestJoinCellName()
    {
        Assert.Equal("A1", Excelize.JoinCellName("A", 1));
        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.JoinCellName("", 0));
        Assert.Equal("invalid column name \"\"", err.Message);
    }

    [Fact]
    public void TestMergeCells()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.MergeCell("Sheet1", "A1", "B2");
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.MergeCell("SheetN", "A1", "B2"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestMergeCells.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestOpenFile()
    {
        Assert.Null(
            Record.Exception(() =>
            {
                Options opt = new Options { Password = "password" };
                File f = Excelize.NewFile();
                f.UpdateLinkedValue();
                f.SaveAs("Book2.xlsx", opt);
                f.Close();
                f = Excelize.OpenFile("Book2.xlsx", opt);
                f.Save();
                f.Close();
                File f2 = Excelize.OpenReader(System.IO.File.ReadAllBytes("Book2.xlsx"));
                f2.Close();
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.OpenFile("Book1"));
        Assert.StartsWith("open Book1", err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            Excelize.OpenReader(
                System.IO.File.ReadAllBytes(
                    Path.GetFullPath(Path.Combine("..", "..", "..", "..", "chart.png"))
                )
            )
        );
        Assert.Equal("zip: not a valid zip file", err.Message);
    }

    [Fact]
    public void TestOutlineLevel()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetColOutlineLevel("Sheet1", "D", 2);
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.SetColOutlineLevel("SheetN", "D", 2)
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestOutlineLevel.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestPivotTable()
    {
        File f = Excelize.NewFile();
        List<string> months = new List<string>
        {
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
        };
        List<int> year = new List<int> { 2017, 2018, 2019 };
        List<string> types = new List<string> { "Meat", "Dairy", "Beverages", "Produce" };
        List<string> region = new List<string> { "East", "West", "North", "South" };
        Random random = new Random();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetSheetRow(
                    "Sheet1",
                    "A1",
                    new List<object> { "Month", "Year", "Type", "Sales", "Region" }
                );
                for (int row = 2; row < 32; row++)
                {
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, row),
                        months[random.Next(12)]
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(2, row),
                        year[random.Next(3)]
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(3, row),
                        types[random.Next(4)]
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(4, row),
                        random.Next(5000)
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(5, row),
                        region[random.Next(4)]
                    );
                }
                f.AddPivotTable(
                    new PivotTableOptions
                    {
                        DataRange = "Sheet1!A1:E31",
                        PivotTableRange = "Sheet1!G2:M34",
                        Name = "PivotTable1",
                        Rows = new PivotTableField[]
                        {
                            new() { Data = "Month", DefaultSubtotal = true },
                            new() { Data = "Year" },
                        },
                        Filter = new PivotTableField[] { new() { Data = "Region" } },
                        Columns = new PivotTableField[]
                        {
                            new() { Data = "Type", DefaultSubtotal = true },
                        },
                        Data = new PivotTableField[]
                        {
                            new()
                            {
                                Data = "Sales",
                                Name = "Summarize",
                                Subtotal = "sum",
                            },
                        },
                        RowGrandTotals = true,
                        ColGrandTotals = true,
                        ShowDrill = true,
                        ShowRowHeaders = true,
                        ShowColHeaders = true,
                        ShowLastColumn = true,
                    }
                );
                f.AddSlicer(
                    "Sheet1",
                    new SlicerOptions
                    {
                        Name = "Month",
                        Cell = "O2",
                        TableSheet = "Sheet1",
                        TableName = "PivotTable1",
                        Caption = "Month",
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddPivotTable(new PivotTableOptions { })
        );
        Assert.Equal(
            "parameter 'PivotTableRange' parsing error: parameter is required",
            err.Message
        );

        err = Assert.Throws<RuntimeError>(() =>
            f.AddSlicer(
                "SheetN",
                new SlicerOptions
                {
                    Name = "Year",
                    Cell = "S2",
                    TableSheet = "Sheet1",
                    TableName = "PivotTable1",
                    Caption = "Year",
                }
            )
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);

        Assert.Null(Record.Exception(() => f.SaveAs("TestAddPivotTable.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestSetSheetName()
    {
        File f = Excelize.NewFile();
        Assert.Null(Record.Exception(() => f.SetSheetName("Sheet1", "Sheet2")));
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.SetSheetName("Sheet2", "[Rename]:\\/?* Maximum 31 characters allowed in sheet title.")
        );
        Assert.Equal("the sheet name length exceeds the 31 characters limit", err.Message);
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestSheetView()
    {
        File f = Excelize.NewFile();
        ViewOptions option = new ViewOptions
        {
            DefaultGridColor = false,
            RightToLeft = false,
            ShowFormulas = false,
            ShowGridLines = false,
            ShowRowColHeaders = false,
            ShowRuler = false,
            ShowZeros = false,
            TopLeftCell = "A1",
            View = "normal",
            ZoomScale = 120,
        };
        Assert.Null(Record.Exception(() => f.SetSheetView("Sheet1", 0, option)));
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.SetSheetView("SheetN", 0, option));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestSheetView.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestSheetVisible()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.NewSheet("Sheet2");
                f.SetSheetVisible("Sheet2", false, true);
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.SetSheetVisible("Sheet:1", true));
        Assert.Equal("the sheet can not contain any of the characters :\\/?*[or]", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestSheetVisible.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestSplitCellName()
    {
        Assert.Equal(("AK", 74), Excelize.SplitCellName("AK74"));
        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.SplitCellName(""));
        Assert.Equal("invalid cell name \"\"", err.Message);
    }

    [Fact]
    public void TestStreamWriter()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                StreamWriter sw = f.NewStreamWriter("Sheet1");
                sw.SetRow("A1", null);
                sw.SetRow("A1", new List<object>());
                for (int r = 4; r < 11; r++)
                {
                    Random random = new Random();
                    List<object> row = new List<object>();
                    for (int i = 1; i < 4; i++)
                    {
                        row.Add(random.Next(640000));
                    }
                    string cell = Excelize.CoordinatesToCellName(1, r, false);
                    sw.SetRow(cell, row);
                }
                sw.Flush();
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.NewStreamWriter("SheetN"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("TestStreamWriter.xlsx")));
        Assert.Empty(f.Close());

        const string errStreamWriterPtr = "can not find stream writer pointer";
        StreamWriter sw = new StreamWriter(0);
        err = Assert.Throws<RuntimeError>(() => sw.SetRow("A1", new List<object> { 1 }));
        Assert.Equal(errStreamWriterPtr, err.Message);
        err = Assert.Throws<RuntimeError>(sw.Flush);
        Assert.Equal(errStreamWriterPtr, err.Message);
    }

    [Fact]
    public void TestStyle()
    {
        File f = Excelize.NewFile();
        Style s = new Style
        {
            Border = new Border[]
            {
                new()
                {
                    Type = "left",
                    Color = "0000FF",
                    Style = 3,
                },
                new()
                {
                    Type = "right",
                    Color = "FF0000",
                    Style = 6,
                },
                new()
                {
                    Type = "top",
                    Color = "00FF00",
                    Style = 4,
                },
                new()
                {
                    Type = "bottom",
                    Color = "FFFF00",
                    Style = 5,
                },
                new()
                {
                    Type = "diagonalUp",
                    Color = "A020F0",
                    Style = 8,
                },
                new()
                {
                    Type = "diagonalDown",
                    Color = "A020F0",
                    Style = 8,
                },
            },
            Font = new Font
            {
                Bold = true,
                Size = 11.5,
                Italic = true,
                Strike = true,
                Color = "FFF000",
                Underline = "single",
                Family = "Times New Roman",
                ColorIndexed = 6,
                ColorTheme = 1,
                ColorTint = 0.11,
                VertAlign = "superscript",
            },
            Fill = new Fill
            {
                Shading = 1,
                Color = new string[] { "00FF00", "FFFF00" },
                Type = "gradient",
            },
            Alignment = new Alignment
            {
                Horizontal = "center",
                Indent = 1,
                JustifyLastLine = true,
                ReadingOrder = 1,
                RelativeIndent = 1,
                ShrinkToFit = true,
                TextRotation = 180,
                Vertical = "center",
                WrapText = true,
            },
            Protection = new Protection { Locked = false, Hidden = true },
            CustomNumFmt = ";;;",
        };
        int styleId = f.NewStyle(s);
        Assert.Equal(1, styleId);
        Style style = f.GetStyle(styleId);
        Assert.Equivalent(s, style);

        Assert.Null(
            Record.Exception(() =>
            {
                f.SetCellStyle("Sheet1", "A1", "B2", styleId);
                f.SetColStyle("Sheet1", "H", styleId);
                f.UpdateLinkedValue();
                f.SetCellInt("Sheet1", "A1", 100);
                f.SetCellBool("Sheet1", "A11", true);
                f.SetCellBool("Sheet1", "A12", false);
                f.SetCellDefault("Sheet1", "A13", "default");
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.SetColStyle("SheetN", "H", styleId));
        Assert.Equal("sheet SheetN does not exist", err.Message);

        List<object?> arr = new()
        {
            null,
            "Hello",
            100,
            123.45,
            true,
            (float)123,
            (long)12345,
            (short)12,
        };
        arr.ForEach(v =>
            Assert.Null(
                Record.Exception(() =>
                {
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, arr.IndexOf(v) + 2),
                        v
                    );
                })
            )
        );
        Assert.Null(
            Record.Exception(() =>
            {
                Assert.Equal("100", f.CalcCellValue("Sheet1", "A4"));
                f.SetActiveSheet(f.NewSheet("Sheet2"));
                Assert.Equal(1, f.GetActiveSheetIndex());
                f.MoveSheet("Sheet2", "Sheet1");
                Assert.Equal(0, f.GetActiveSheetIndex());
            })
        );
        Assert.Null(
            Record.Exception(() =>
            {
                Assert.Equal("100", f.GetCellValue("Sheet1", "A4"));
            })
        );
        Assert.Equal(
            new List<List<string>>
            {
                new() { },
                new() { },
                new() { "Hello" },
                new() { "100" },
                new() { "123.45" },
                new() { "TRUE" },
                new() { "123" },
                new() { "12345" },
                new() { "12" },
                new() { },
                new() { "TRUE" },
                new() { "FALSE" },
                new() { "default" },
            },
            f.GetRows("Sheet1")
        );
        Assert.Null(Record.Exception(() => f.CopySheet(0, f.NewSheet("Sheet3"))));
        Assert.Null(Record.Exception(() => f.DeleteSheet("Sheet3")));
        Assert.Null(Record.Exception(() => f.DuplicateRow("Sheet2", 2)));
        Assert.Null(Record.Exception(() => f.DuplicateRowTo("Sheet2", 2, 7)));
        err = Assert.Throws<RuntimeError>(() => f.DeleteSheet("Sheet:1"));
        Assert.Equal("the sheet can not contain any of the characters :\\/?*[or]", err.Message);
        Assert.Null(Record.Exception(() => f.SaveAs("Book1.xlsx")));
        Assert.Empty(f.Close());

        err = Assert.Throws<RuntimeError>(() => Excelize.CoordinatesToCellName(0, 1));
        Assert.Equal("invalid cell reference [0, 1]", err.Message);

        f = new File(0);
        string expected = "can not find file pointer";
        err = Assert.Throws<RuntimeError>(() => f.AddChart("Sheet1", "A1", new Chart()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddChartSheet("Sheet1", new Chart()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddComment("Sheet1", new Comment()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.AddHeaderFooterImage("Sheet1", new HeaderFooterImageOptions())
        );
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.AddIgnoredErrors("Sheet1", "A1", IgnoredErrorsType.IgnoredErrorsEvalError)
        );
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.AddPictureFromBytes("Sheet1", "A1", new Picture())
        );
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddVBAProject(Array.Empty<byte>()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.CopySheet(1, 2));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DeleteChart("Sheet1", "A1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DeleteComment("Sheet1", "A1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DeletePicture("Sheet1", "A1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DeleteSheet("Sheet1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DeleteSlicer("x"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DuplicateRow("Sheet1", 1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.DuplicateRowTo("Sheet1", 1, 2));
        Assert.Equal(expected, err.Message);
        Assert.Equal(0, f.GetActiveSheetIndex());
        err = Assert.Throws<RuntimeError>(() => f.GetAppProps());
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetCalcProps());
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetCellFormula("Sheet1", "A1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetCellValue("Sheet1", "A1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetRows("Sheet1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetStyle(1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.MergeCell("Sheet1", "A1", "B2"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.MoveSheet("Sheet2", "Sheet1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.NewSheet("Sheet1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.NewStyle(s));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.Save());
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetActiveSheet(1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetAppProps(new AppProperties()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCalcProps(new CalcPropsOptions()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellBool("Sheet1", "A1", true));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellDefault("Sheet1", "A13", "default"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellFormula("Sheet1", "A1", "=A2"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellStyle("Sheet1", "A1", "B2", styleId));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellInt("Sheet1", "A1", 100));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellValue("Sheet1", "A1", 100));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetColOutlineLevel("Sheet1", "A", 1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetColStyle("Sheet1", "H", 1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetSheetName("Sheet1", "Sheet2"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.SetSheetRow("Sheet1", "A1", new List<object> { 1 })
        );
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetSheetView("Sheet1", -1, null));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetSheetVisible("Sheet1", true));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetWorkbookProps(new WorkbookPropsOptions()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.UpdateLinkedValue());
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SaveAs("Book1.xlsx"));
        Assert.Equal(expected, err.Message);
        Assert.Equal(expected, f.Close());
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct C1
    {
        public int ALen;
        public int* A;
        public int BLen;
        public int* B;
        public int CLen;
        public sbyte** C;
        public int DLen;
        public TypesC.Interface* D;
        public double* E;
        public float* F;
        public long* G;
        public short* H;
        public byte* I;
        public uint* J;
        public ulong* K;
        public ushort* L;
        public sbyte** M;
        public bool* N;
    }

    public struct CsT1
    {
        public int[]? A;
        public int?[]? B;
        public string?[]? C;
        public Interface?[]? D;
        public double? E;
        public float? F;
        public long? G;
        public short? H;
        public byte? I;
        public uint? J;
        public ulong? K;
        public ushort? L;
        public string? M;
        public bool? N;
    }

    [Fact]
    public unsafe void TestTypeConvert()
    {
        CsT1 expected = new CsT1
        {
            A = new int[] { 1, 2 },
            B = new int?[] { 3, 4, null },
            C = new string?[] { "a", "b" },
            D = new Interface?[]
            {
                new Interface { Type = 0, Integer = 100 },
                null,
            },
            E = 123.45,
            F = 12.3f,
            G = 123456,
            H = 123,
            I = 12,
            J = 123U,
            K = 123456UL,
            L = 123,
            M = "text",
            N = true,
        };
        C1 cT1 = (C1)Lib.CsToC(expected, new C1());
        CsT1 csT1 = (CsT1)Lib.CToCs(cT1, new CsT1());
        Assert.Equivalent(expected, csT1);
        Assert.Null(Lib.CsToC(null, new CsT1()));
        Assert.Null(Lib.CToCs(null, new C1()));
        sbyte value = -42;
        IntPtr intPtr = (IntPtr)(&value);
        Assert.Null(Lib.UnmarshalPrimitiveValue(intPtr, typeof(string)));
        Assert.Null(Lib.UnmarshalPrimitiveValue(IntPtr.Zero, typeof(string)));
    }

    [Fact]
    public void TestWorkbookProps()
    {
        File f = Excelize.NewFile();
        WorkbookPropsOptions opts = new WorkbookPropsOptions
        {
            Date1904 = true,
            FilterPrivacy = true,
            CodeName = "code",
        };
        Assert.Null(Record.Exception(() => f.SetWorkbookProps(opts)));
        Assert.Null(Record.Exception(() => f.SaveAs("TestWorkbookProps.xlsx")));
        Assert.Empty(f.Close());
    }
}
