// Copyright 2025 - 2026 The excelize Authors. All rights reserved. Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.
//
// Package excelize-cs is a C# port of Go Excelize library, providing a set of
// functions that allow you to write and read from XLAM / XLSM / XLSX / XLTM /
// XLTX files. Supports reading and writing spreadsheet documents generated by
// Microsoft Excel™ 2007 and later. Supports complex components by high
// compatibility, and provided streaming API for generating or reading data from
// a worksheet with huge amounts of data. This library needs .NET version 6, C#
// version 10 or later.

namespace ExcelizeCs.Tests;

using System.Runtime.InteropServices;
using Xunit;

public class UnitTest
{
    [Fact]
    public void TestDllImportResolver()
    {
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            Lib.DllImportResolver("lib", null, null)
        );
        Assert.Equal(Lib.ErrUnsupportedPlatformOrArch, err.Message);
    }

    [Fact]
    public void TestStyle()
    {
        File f = Excelize.NewFile();
        Style s = new Style
        {
            Border = new Border[]
            {
                new()
                {
                    Type = "left",
                    Color = "0000FF",
                    Style = 3,
                },
                new()
                {
                    Type = "right",
                    Color = "FF0000",
                    Style = 6,
                },
                new()
                {
                    Type = "top",
                    Color = "00FF00",
                    Style = 4,
                },
                new()
                {
                    Type = "bottom",
                    Color = "FFFF00",
                    Style = 5,
                },
                new()
                {
                    Type = "diagonalUp",
                    Color = "A020F0",
                    Style = 8,
                },
                new()
                {
                    Type = "diagonalDown",
                    Color = "A020F0",
                    Style = 8,
                },
            },
            Font = new Font
            {
                Bold = true,
                Size = 11.5,
                Italic = true,
                Strike = true,
                Color = "FFF000",
                Underline = "single",
                Family = "Times New Roman",
                ColorIndexed = 6,
                ColorTheme = 1,
                ColorTint = 0.11,
                VertAlign = "superscript",
            },
            Fill = new Fill
            {
                Shading = 1,
                Color = new string[] { "00FF00", "FFFF00" },
                Type = "gradient",
            },
            Alignment = new Alignment
            {
                Horizontal = "center",
                Indent = 1,
                JustifyLastLine = true,
                ReadingOrder = 1,
                RelativeIndent = 1,
                ShrinkToFit = true,
                TextRotation = 180,
                Vertical = "center",
                WrapText = true,
            },
            Protection = new Protection { Locked = false, Hidden = true },
            CustomNumFmt = ";;;",
        };
        int styleId = f.NewStyle(s);
        Assert.Equal(1, styleId);
        Style style = f.GetStyle(styleId);
        Assert.Equivalent(s, style);

        Assert.Null(Record.Exception(() => f.SetCellStyle("Sheet1", "A1", "B2", styleId)));
        Assert.Null(Record.Exception(() => f.UpdateLinkedValue()));
        Assert.Null(Record.Exception(() => f.SetCellInt("Sheet1", "A1", 100)));

        List<object?> arr = new()
        {
            null,
            "Hello",
            100,
            123.45,
            true,
            (float)123,
            (long)12345,
            (short)12,
        };
        arr.ForEach(v =>
            Assert.Null(
                Record.Exception(() =>
                {
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, arr.IndexOf(v) + 2),
                        v
                    );
                })
            )
        );
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetActiveSheet(f.NewSheet("Sheet2"));
            })
        );
        Assert.Null(
            Record.Exception(() =>
            {
                Assert.Equal("100", f.GetCellValue("Sheet1", "A4"));
            })
        );
        Assert.Equal(
            new List<List<string>>
            {
                new() { },
                new() { },
                new() { "Hello" },
                new() { "100" },
                new() { "123.45" },
                new() { "TRUE" },
                new() { "123" },
                new() { "12345" },
                new() { "12" },
            },
            f.GetRows("Sheet1")
        );
        Assert.Null(Record.Exception(() => f.SaveAs("Book1.xlsx")));
        Assert.Empty(f.Close());

        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.CoordinatesToCellName(0, 1));
        Assert.Equal("invalid cell reference [0, 1]", err.Message);

        f = new File(0);
        string expected = "can not find file pointer";
        err = Assert.Throws<RuntimeError>(() => f.AddChart("Sheet1", "A1", new Chart()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddChartSheet("Sheet1", new Chart()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddComment("Sheet1", new Comment()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.AddPictureFromBytes("Sheet1", "A1", new Picture())
        );
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.AddVBAProject(Array.Empty<byte>()));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetCellValue("Sheet1", "A1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetRows("Sheet1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.GetStyle(1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.NewSheet("Sheet1"));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.NewStyle(s));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.Save());
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetActiveSheet(1));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellStyle("Sheet1", "A1", "B2", styleId));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellInt("Sheet1", "A1", 100));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SetCellValue("Sheet1", "A1", 100));
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.SetSheetRow("Sheet1", "A1", new List<object> { 1 })
        );
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.UpdateLinkedValue());
        Assert.Equal(expected, err.Message);
        err = Assert.Throws<RuntimeError>(() => f.SaveAs("Book1.xlsx"));
        Assert.Equal(expected, err.Message);
        Assert.Equal(expected, f.Close());
    }

    [Fact]
    public void TestStreamWriter()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                StreamWriter sw = f.NewStreamWriter("Sheet1");
                sw.SetRow("A1", null);
                sw.SetRow("A1", new List<object>());
                for (int r = 4; r < 11; r++)
                {
                    Random random = new Random();
                    List<object> row = new List<object>();
                    for (int i = 1; i < 4; i++)
                    {
                        row.Add(random.Next(640000));
                    }
                    string cell = Excelize.CoordinatesToCellName(1, r, false);
                    sw.SetRow(cell, row);
                }
                sw.Flush();
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.NewStreamWriter("SheetN"));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(
            Record.Exception(() =>
            {
                f.SaveAs("TestStreamWriter.xlsx");
            })
        );
        Assert.Empty(f.Close());

        const string errStreamWriterPtr = "can not find stream writer pointer";
        StreamWriter sw = new StreamWriter(0);
        err = Assert.Throws<RuntimeError>(() => sw.SetRow("A1", new List<object> { 1 }));
        Assert.Equal(errStreamWriterPtr, err.Message);
        err = Assert.Throws<RuntimeError>(sw.Flush);
        Assert.Equal(errStreamWriterPtr, err.Message);
    }

    [Fact]
    public void TestAddChart()
    {
        File f = Excelize.NewFile();
        List<List<object?>> data = new List<List<object?>>
        {
            new() { null, "Apple", "Orange", "Pear" },
            new() { "Small", 2, 3, 3 },
            new() { "Normal", 5, 2, 4 },
            new() { "Large", 6, 7, 8 },
        };
        Assert.Null(Record.Exception(() => f.SetSheetRow("Sheet1", "A1", null)));
        Assert.Null(Record.Exception(() => f.SetSheetRow("Sheet1", "A1", new List<object>())));
        foreach (List<object?> row in data)
        {
            Assert.Null(
                Record.Exception(() =>
                    f.SetSheetRow(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, data.IndexOf(row) + 1),
                        row
                    )
                )
            );
        }
        Chart chart = new Chart
        {
            Type = ChartType.Col3DClustered,
            Series = new ChartSeries[]
            {
                new()
                {
                    Name = "Sheet1!$A$2",
                    Categories = "Sheet1!$B$1:$D$1",
                    Values = "Sheet1!$B$2:$D$2",
                },
                new()
                {
                    Name = "Sheet1!$A$3",
                    Categories = "Sheet1!$B$1:$D$1",
                    Values = "Sheet1!$B$3:$D$3",
                },
                new()
                {
                    Name = "Sheet1!$A$4",
                    Categories = "Sheet1!$B$1:$D$1",
                    Values = "Sheet1!$B$4:$D$4",
                },
            },
            Title = new RichTextRun[] { new() { Text = "Fruit 3D Clustered Column Chart" } },
        };
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddChart("Sheet1", "E1", chart);
                f.AddChart("Sheet1", "E16", chart, chart);
                f.AddChart("Sheet1", "E31", chart, null);
                f.AddChart("Sheet1", "E46", chart, Array.Empty<Chart>());
                f.AddChartSheet("Sheet2", chart);
                f.AddChartSheet("Sheet3", chart, chart);
                f.AddChartSheet("Sheet4", chart, null);
                f.AddChartSheet("Sheet5", chart, Array.Empty<Chart>());
            })
        );
        Assert.Null(Record.Exception(() => f.SaveAs("TestAddChart.xlsx")));
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddComment()
    {
        File f = Excelize.NewFile();
        Comment comment = new Comment
        {
            Cell = "A5",
            Author = "Excelize",
            Paragraph = new RichTextRun[]
            {
                new()
                {
                    Text = "Excelize: ",
                    Font = new Font { Bold = true },
                },
                new() { Text = "This is a comment." },
            },
            Height = 40,
            Width = 180,
        };
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddComment("Sheet1", null);
                f.AddComment("Sheet1", comment);
                f.SaveAs("TestComment.xlsx");
            })
        );
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddPicture()
    {
        File f = Excelize.NewFile();
        string filePath = Path.GetFullPath(Path.Combine("..", "..", "..", "..", "chart.png"));
        byte[] pic = System.IO.File.ReadAllBytes(filePath);
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddPicture("Sheet1", "A1", filePath, null);
                f.AddPicture(
                    "Sheet1",
                    "A1",
                    filePath,
                    new GraphicOptions
                    {
                        PrintObject = true,
                        ScaleX = 0.1,
                        ScaleY = 0.1,
                        Locked = false,
                    }
                );
                f.AddPictureFromBytes(
                    "Sheet1",
                    "A3",
                    new Picture
                    {
                        Extension = ".png",
                        File = pic,
                        Format = new GraphicOptions
                        {
                            PrintObject = true,
                            ScaleX = 0.1,
                            ScaleY = 0.1,
                            Locked = false,
                        },
                        InsertType = PictureInsertType.PictureInsertTypePlaceOverCells,
                    }
                );
                f.SaveAs("TestAddPicture.xlsx");
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddPicture("SheetN", "A1", filePath, null)
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddFormControl()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "A3",
                        Macro = "Button1_Click",
                        Width = 140,
                        Height = 60,
                        Text = "Button 1\r\n",
                        Paragraph = new RichTextRun[]
                        {
                            new()
                            {
                                Font = new Font
                                {
                                    Bold = true,
                                    Italic = true,
                                    Underline = "single",
                                    Family = "Times New Roman",
                                    Size = 14,
                                    Color = "777777",
                                },
                                Text = "C1=A1+B1",
                            },
                        },
                        Type = FormControlType.FormControlButton,
                        Format = new GraphicOptions
                        {
                            PrintObject = true,
                            Positioning = "absolute",
                        },
                    }
                );
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "A1",
                        Macro = "Button1_Click",
                        Text = "Option Button 1",
                        Type = FormControlType.FormControlOptionButton,
                    }
                );
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "B1",
                        Type = FormControlType.FormControlSpinButton,
                        Width = 15,
                        Height = 40,
                        CurrentVal = 7,
                        MinVal = 5,
                        MaxVal = 10,
                        IncChange = 1,
                        CellLink = "A1",
                    }
                );
                f.AddFormControl(
                    "Sheet1",
                    new FormControl
                    {
                        Cell = "B3",
                        Type = FormControlType.FormControlScrollBar,
                        Width = 140,
                        Height = 20,
                        CurrentVal = 50,
                        MinVal = 10,
                        MaxVal = 100,
                        PageChange = 1,
                        CellLink = "A1",
                        Horizontally = true,
                    }
                );
                f.SetSheetProps("Sheet1", new SheetPropsOptions { CodeName = "Sheet1" });
                f.AddFormControl("Sheet1", null);
                f.AddVBAProject(
                    System.IO.File.ReadAllBytes(
                        Path.GetFullPath(Path.Combine("..", "..", "..", "vbaProject.bin"))
                    )
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddFormControl("SheetN", new FormControl { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            f.SetSheetProps("SheetN", new SheetPropsOptions { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(
            Record.Exception(() =>
            {
                f.SaveAs("TestAddFormControl.xlsm");
            })
        );
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestAddShape()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.AddShape(
                    "Sheet1",
                    new Shape
                    {
                        Cell = "G6",
                        Type = "rect",
                        Line = new ShapeLine { Color = "4286F4", Width = 1.2 },
                        Fill = new Fill { Color = new string[] { "8EB9FF" }, Pattern = 1 },
                        Paragraph = new RichTextRun[]
                        {
                            new()
                            {
                                Text = "Rectangle Shape",
                                Font = new Font
                                {
                                    Bold = true,
                                    Italic = true,
                                    Family = "Times New Roman",
                                    Size = 19,
                                    Color = "777777",
                                    Underline = "sng",
                                },
                            },
                        },
                        Width = 180,
                        Height = 40,
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => f.AddShape("SheetN", new Shape { }));
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(
            Record.Exception(() =>
            {
                f.SaveAs("TestAddShape.xlsx");
            })
        );
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestCoordinates()
    {
        var (col, row) = Excelize.CellNameToCoordinates("Z3");
        Assert.Equal((26, 3), (col, row));
        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.CellNameToCoordinates("A"));
        Assert.Equal(
            "cannot convert cell \"A\" to coordinates: invalid cell name \"A\"",
            err.Message
        );
        Assert.Equal(26, Excelize.ColumnNameToNumber(Excelize.ColumnNumberToName(26)));
        err = Assert.Throws<RuntimeError>(() => Excelize.ColumnNameToNumber("-"));
        Assert.Equal("invalid column name \"-\"", err.Message);
        err = Assert.Throws<RuntimeError>(() => Excelize.ColumnNumberToName(0));
        Assert.Equal(
            "the column number must be greater than or equal to 1 and less than or equal to 16384",
            err.Message
        );
    }

    [Fact]
    public void TestHeaderFooter()
    {
        File f = Excelize.NewFile();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetHeaderFooter(
                    "Sheet1",
                    new HeaderFooterOptions
                    {
                        DifferentFirst = true,
                        DifferentOddEven = true,
                        OddHeader = "&R&P",
                        OddFooter = "&C&F",
                        EvenHeader = "&L&P",
                        EvenFooter = "&L&D&R&T",
                        FirstHeader = "&CCenter &\"-,Bold\"Bold&\"-,Regular\"HeaderU+000A&D",
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.SetHeaderFooter("SheetN", new HeaderFooterOptions { })
        );
        Assert.Equal("sheet SheetN does not exist", err.Message);
        Assert.Null(
            Record.Exception(() =>
            {
                f.SaveAs("TestHeaderFooter.xlsx");
            })
        );
        Assert.Empty(f.Close());
    }

    [Fact]
    public void TestOpenFile()
    {
        Assert.Null(
            Record.Exception(() =>
            {
                Options opt = new Options { Password = "password" };
                File f = Excelize.NewFile();
                f.UpdateLinkedValue();
                f.SaveAs("Book2.xlsx", opt);
                f.Close();
                f = Excelize.OpenFile("Book2.xlsx", opt);
                f.Save();
                f.Close();
                File f2 = Excelize.OpenReader(System.IO.File.ReadAllBytes("Book2.xlsx"));
                f2.Close();
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() => Excelize.OpenFile("Book1"));
        Assert.StartsWith("open Book1", err.Message);
        err = Assert.Throws<RuntimeError>(() =>
            Excelize.OpenReader(
                System.IO.File.ReadAllBytes(
                    Path.GetFullPath(Path.Combine("..", "..", "..", "..", "chart.png"))
                )
            )
        );
        Assert.Equal("zip: not a valid zip file", err.Message);
    }

    [Fact]
    public void TestPivotTable()
    {
        File f = Excelize.NewFile();
        List<string> months = new List<string>
        {
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
        };
        List<int> year = new List<int> { 2017, 2018, 2019 };
        List<string> types = new List<string> { "Meat", "Dairy", "Beverages", "Produce" };
        List<string> region = new List<string> { "East", "West", "North", "South" };
        Random random = new Random();
        Assert.Null(
            Record.Exception(() =>
            {
                f.SetSheetRow(
                    "Sheet1",
                    "A1",
                    new List<object> { "Month", "Year", "Type", "Sales", "Region" }
                );
                for (int row = 2; row < 32; row++)
                {
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(1, row),
                        months[random.Next(12)]
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(2, row),
                        year[random.Next(3)]
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(3, row),
                        types[random.Next(4)]
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(4, row),
                        random.Next(5000)
                    );
                    f.SetCellValue(
                        "Sheet1",
                        Excelize.CoordinatesToCellName(5, row),
                        region[random.Next(4)]
                    );
                }
                f.AddPivotTable(
                    new PivotTableOptions
                    {
                        DataRange = "Sheet1!A1:E31",
                        PivotTableRange = "Sheet1!G2:M34",
                        Rows = new PivotTableField[]
                        {
                            new() { Data = "Month", DefaultSubtotal = true },
                            new() { Data = "Year" },
                        },
                        Filter = new PivotTableField[] { new() { Data = "Region" } },
                        Columns = new PivotTableField[]
                        {
                            new() { Data = "Type", DefaultSubtotal = true },
                        },
                        Data = new PivotTableField[]
                        {
                            new()
                            {
                                Data = "Sales",
                                Name = "Summarize",
                                Subtotal = "sum",
                            },
                        },
                        RowGrandTotals = true,
                        ColGrandTotals = true,
                        ShowDrill = true,
                        ShowRowHeaders = true,
                        ShowColHeaders = true,
                        ShowLastColumn = true,
                    }
                );
            })
        );
        RuntimeError err = Assert.Throws<RuntimeError>(() =>
            f.AddPivotTable(new PivotTableOptions { })
        );
        Assert.Equal(
            "parameter 'PivotTableRange' parsing error: parameter is required",
            err.Message
        );
        Assert.Null(
            Record.Exception(() =>
            {
                f.SaveAs("TestAddPivotTable.xlsx");
            })
        );
        Assert.Empty(f.Close());
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct C1
    {
        public int ALen;
        public int* A;
        public int BLen;
        public int* B;
        public int CLen;
        public sbyte** C;
        public int DLen;
        public TypesC.Interface* D;
        public double* E;
        public float* F;
        public long* G;
        public short* H;
        public byte* I;
        public uint* J;
        public ulong* K;
        public ushort* L;
        public sbyte** M;
        public bool* N;
    }

    public struct CsT1
    {
        public int[]? A;
        public int?[]? B;
        public string?[]? C;
        public Interface?[]? D;
        public double? E;
        public float? F;
        public long? G;
        public short? H;
        public byte? I;
        public uint? J;
        public ulong? K;
        public ushort? L;
        public string? M;
        public bool? N;
    }

    [Fact]
    public unsafe void TestTypeConvert()
    {
        CsT1 expected = new CsT1
        {
            A = new int[] { 1, 2 },
            B = new int?[] { 3, 4, null },
            C = new string?[] { "a", "b" },
            D = new Interface?[]
            {
                new Interface { Type = 0, Integer = 100 },
                null,
            },
            E = 123.45,
            F = 12.3f,
            G = 123456,
            H = 123,
            I = 12,
            J = 123U,
            K = 123456UL,
            L = 123,
            M = "text",
            N = true,
        };
        C1 cT1 = (C1)Lib.CsToC(expected, new C1());
        CsT1 csT1 = (CsT1)Lib.CToCs(cT1, new CsT1());
        Assert.Equivalent(expected, csT1);
        Assert.Null(Lib.CsToC(null, new CsT1()));
        Assert.Null(Lib.CToCs(null, new C1()));
        sbyte value = -42;
        IntPtr intPtr = (IntPtr)(&value);
        Assert.Null(Lib.UnmarshalPrimitiveValue(intPtr, typeof(string)));
    }
}
