// Copyright 2025 - 2026 The excelize Authors. All rights reserved. Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.
//
// Package excelize-cs is a C# port of Go Excelize library, providing a set of
// functions that allow you to write and read from XLAM / XLSM / XLSX / XLTM /
// XLTX files. Supports reading and writing spreadsheet documents generated by
// Microsoft Excel™ 2007 and later. Supports complex components by high
// compatibility, and provided streaming API for generating or reading data from
// a worksheet with huge amounts of data. This library needs .NET version 6, C#
// version 10 or later.

#nullable enable

namespace ExcelizeCs
{
    /// <summary>
    /// This section defines the currently supported country code types
    /// enumeration for apply number format.
    /// </summary>
    public enum CultureName : byte
    {
        CultureNameUnknown = 0,
        CultureNameEnUS = 1,
        CultureNameJaJP = 2,
        CultureNameKoKR = 3,
        CultureNameZhCN = 4,
        CultureNameZhTW = 5,
    }

    /// <summary>
    /// This section defines the cell value types enumeration.
    /// </summary>
    public enum CellType : byte
    {
        CellTypeUnset = 0,
        CellTypeBool = 1,
        CellTypeDate = 2,
        CellTypeError = 3,
        CellTypeFormula = 4,
        CellTypeInlineString = 5,
        CellTypeNumber = 6,
        CellTypeSharedString = 7,
    }

    /// <summary>
    /// FormControlType is the type of supported form controls.
    /// </summary>
    public enum FormControlType : byte
    {
        FormControlNote = 0,
        FormControlButton = 1,
        FormControlOptionButton = 2,
        FormControlSpinButton = 3,
        FormControlCheckBox = 4,
        FormControlGroupBox = 5,
        FormControlLabel = 6,
        FormControlScrollBar = 7,
    }

    /// <summary>
    /// ChartDashType defines the currently supported chart dash types
    /// enumeration.
    /// </summary>
    public enum ChartDashType : byte
    {
        ChartDashUnset = 0,
        ChartDashSolid = 1,
        ChartDashDot = 2,
        ChartDashDash = 3,
        ChartDashLgDash = 4,
        ChartDashSashDot = 5,
        ChartDashLgDashDot = 6,
        ChartDashLgDashDotDot = 7,
        ChartDashSysDash = 8,
        ChartDashSysDot = 9,
        ChartDashSysDashDot = 10,
        ChartDashSysDashDotDot = 11,
    }

    /// <summary>
    /// ChartLineType defines the currently supported chart line types
    /// enumeration.
    /// </summary>
    public enum ChartLineType : byte
    {
        ChartLineUnset = 0,
        ChartLineSolid = 1,
        ChartLineNone = 2,
        ChartLineAutomatic = 3,
    }

    /// <summary>
    /// ChartType defines the currently supported chart types enumeration.
    /// </summary>
    public enum ChartType : byte
    {
        Area = 0,
        AreaStacked = 1,
        AreaPercentStacked = 2,
        Area3D = 3,
        Area3DStacked = 4,
        Area3DPercentStacked = 5,
        Bar = 6,
        BarStacked = 7,
        BarPercentStacked = 8,
        Bar3DClustered = 9,
        Bar3DStacked = 10,
        Bar3DPercentStacked = 11,
        Bar3DConeClustered = 12,
        Bar3DConeStacked = 13,
        Bar3DConePercentStacked = 14,
        Bar3DPyramidClustered = 15,
        Bar3DPyramidStacked = 16,
        Bar3DPyramidPercentStacked = 17,
        Bar3DCylinderClustered = 18,
        Bar3DCylinderStacked = 19,
        Bar3DCylinderPercentStacked = 20,
        Col = 21,
        ColStacked = 22,
        ColPercentStacked = 23,
        Col3D = 24,
        Col3DClustered = 25,
        Col3DStacked = 26,
        Col3DPercentStacked = 27,
        Col3DCone = 28,
        Col3DConeClustered = 29,
        Col3DConeStacked = 30,
        Col3DConePercentStacked = 31,
        Col3DPyramid = 32,
        Col3DPyramidClustered = 33,
        Col3DPyramidStacked = 34,
        Col3DPyramidPercentStacked = 35,
        Col3DCylinder = 36,
        Col3DCylinderClustered = 37,
        Col3DCylinderStacked = 38,
        Col3DCylinderPercentStacked = 39,
        Doughnut = 40,
        Line = 41,
        Line3D = 42,
        Pie = 43,
        Pie3D = 44,
        PieOfPie = 45,
        BarOfPie = 46,
        Radar = 47,
        Scatter = 48,
        Surface3D = 49,
        WireframeSurface3D = 50,
        Contour = 51,
        WireframeContour = 52,
        Bubble = 53,
        Bubble3D = 54,
        StockHighLowClose = 55,
        StockOpenHighLowClose = 56,
    }

    /// <summary>
    /// ChartDataLabelPositionType is the type of chart data labels position.
    /// enumeration.
    /// </summary>
    public enum ChartDataLabelPositionType : byte
    {
        ChartDataLabelsPositionUnset = 0,
        ChartDataLabelsPositionBestFit = 1,
        ChartDataLabelsPositionBelow = 2,
        ChartDataLabelsPositionCenter = 3,
        ChartDataLabelsPositionInsideBase = 4,
        ChartDataLabelsPositionInsideEnd = 5,
        ChartDataLabelsPositionLeft = 6,
        ChartDataLabelsPositionOutsideEnd = 7,
        ChartDataLabelsPositionRight = 8,
        ChartDataLabelsPositionAbove = 9,
    }

    /// <summary>
    /// ChartTickLabelPositionType is the type of supported chart tick label
    /// enumeration.
    /// </summary>
    public enum ChartTickLabelPositionType : byte
    {
        ChartTickLabelNextToAxis = 0,
        ChartTickLabelHigh = 1,
        ChartTickLabelLow = 2,
        ChartTickLabelNone = 3,
    }

    /// <summary>
    /// HeaderFooterImagePositionType is the type of header and footer image
    /// position.
    /// </summary>
    public enum HeaderFooterImagePositionType : byte
    {
        HeaderFooterImagePositionLeft = 0,
        HeaderFooterImagePositionCenter = 1,
        HeaderFooterImagePositionRight = 2,
    }

    /// <summary>
    /// IgnoredErrorsType is the type of ignored errors.
    /// </summary>
    public enum IgnoredErrorsType : byte
    {
        IgnoredErrorsEvalError = 0,
        IgnoredErrorsTwoDigitTextYear = 1,
        IgnoredErrorsNumberStoredAsText = 2,
        IgnoredErrorsFormula = 3,
        IgnoredErrorsFormulaRange = 4,
        IgnoredErrorsUnlockedFormula = 5,
        IgnoredErrorsEmptyCellReference = 6,
        IgnoredErrorsListDataValidation = 7,
        IgnoredErrorsCalculatedColumn = 8,
    }

    /// <summary>
    /// PictureInsertType defines the type of the picture has been inserted into
    /// the worksheet.
    /// </summary>
    public enum PictureInsertType : byte
    {
        PictureInsertTypePlaceOverCells = 0,
        PictureInsertTypePlaceInCell = 1,
        PictureInsertTypeIMAGE = 2,
        PictureInsertTypeDISPIMG = 3,
    }

    /// <summary>
    ///
    /// </summary>
    public struct Interface
    {
        public int Type;
        public int Integer;
        public int Integer32;
        public string String;
        public double Float;
        public bool Boolean;
    }

    /// <summary>
    /// Options define the options for opening and reading the spreadsheet.
    /// </summary>
    public struct Options
    {
        public uint MaxCalcIterations;
        public string Password;
        public bool RawCellValue;
        public long UnzipSizeLimit;
        public long UnzipXMLSizeLimit;
        public string TmpDir;
        public string ShortDatePattern;
        public string LongDatePattern;
        public string LongTimePattern;
        public CultureName CultureInfo;
    }

    /// <summary>
    /// AppProperties directly maps the document application properties.
    /// </summary>
    public struct AppProperties
    {
        public string Application;
        public bool ScaleCrop;
        public int DocSecurity;
        public string Company;
        public bool LinksUpToDate;
        public bool HyperlinksChanged;
        public string AppVersion;
    }

    /// <summary>
    /// CalcPropsOptions defines the collection of properties the application
    /// uses to record calculation status and details.
    /// </summary>
    public struct CalcPropsOptions
    {
        public uint? CalcID;
        public string? CalcMode;
        public bool? FullCalcOnLoad;
        public string? RefMode;
        public bool? Iterate;
        public uint? IterateCount;
        public float? IterateDelta;
        public bool? FullPrecision;
        public bool? CalcCompleted;
        public bool? CalcOnSave;
        public bool? ConcurrentCalc;
        public uint? ConcurrentManualCount;
        public bool? ForceFullCalc;
    };

    /// <summary>
    /// Alignment directly maps the alignment settings of the cells.
    /// </summary>
    public struct Alignment
    {
        public string Horizontal;
        public int Indent;
        public bool JustifyLastLine;
        public uint ReadingOrder;
        public int RelativeIndent;
        public bool ShrinkToFit;
        public int TextRotation;
        public string Vertical;
        public bool WrapText;
    }

    /// <summary>
    /// Border directly maps the border settings of the cells.
    /// </summary>
    public struct Border
    {
        public string Type;
        public string Color;
        public int Style;
    }

    /// <summary>
    /// Font directly maps the font settings of the fonts.
    /// </summary>
    public struct Font
    {
        public bool Bold;
        public bool Italic;
        public string Underline;
        public string Family;
        public double Size;
        public bool Strike;
        public string Color;
        public int ColorIndexed;
        public int? ColorTheme;
        public double ColorTint;
        public string VertAlign;
        public int? Charset;
    }

    /// <summary>
    /// Fill directly maps the fill settings of the cells.
    /// </summary>
    public struct Fill
    {
        public string Type;
        public int Pattern;
        public string[]? Color;
        public int Shading;
        public int Transparency;
    }

    /// <summary>
    /// Protection directly maps the protection settings of the cells.
    /// </summary>
    public struct Protection
    {
        public bool Locked;
        public bool Hidden;
    }

    /// <summary>
    /// AutoFilterOptions directly maps the auto filter settings.
    /// </summary>
    public struct AutoFilterOptions
    {
        public string Column;
        public string Expression;
    }

    /// <summary>
    /// FormulaOpts can be passed to SetCellFormula to use other formula types.
    /// </summary>
    public struct FormulaOpts
    {
        public string? Type;
        public string? Ref;
    }

    /// <summary>
    /// HeaderFooterOptions directly maps the settings of header and footer.
    /// </summary>
    public struct HeaderFooterOptions
    {
        public bool? AlignWithMargins;
        public bool DifferentFirst;
        public bool DifferentOddEven;
        public bool? ScaleWithDoc;
        public string OddHeader;
        public string OddFooter;
        public string EvenHeader;
        public string EvenFooter;
        public string FirstHeader;
        public string FirstFooter;
    }

    /// <summary>
    /// HyperlinkOpts can be passed to SetCellHyperlink to set optional
    /// hyperlink attributes (e.g. display value)
    /// </summary>
    public struct HyperlinkOpts
    {
        public string? Display;
        public string? Tooltip;
    }

    /// <summary>
    /// HeaderFooterImageOptions defines the settings for an image to be
    ///  accessible from the worksheet header and footer options.
    /// </summary>
    public struct HeaderFooterImageOptions
    {
        public HeaderFooterImagePositionType Position;
        public byte[]? File;
        public bool IsFooter;
        public bool FirstPage;
        public string Extension;
        public string Width;
        public string Height;
    }

    /// <summary>
    /// Style directly maps the style settings of the cells.
    /// </summary>
    public struct Style
    {
        public Border[]? Border;
        public Fill Fill;
        public Font? Font;
        public Alignment? Alignment;
        public Protection? Protection;
        public int NumFmt;
        public int? DecimalPlaces;
        public string? CustomNumFmt;
        public bool NegRed;
    }

    /// <summary>
    /// GraphicOptions directly maps the format settings of the picture.
    /// </summary>
    public struct GraphicOptions
    {
        public string AltText;
        public string Name;
        public bool? PrintObject;
        public bool? Locked;
        public bool LockAspectRatio;
        public bool AutoFit;
        public bool AutoFitIgnoreAspect;
        public int OffsetX;
        public int OffsetY;
        public double ScaleX;
        public double ScaleY;
        public string Hyperlink;
        public string HyperlinkType;
        public string Positioning;
    }

    /// <summary>
    /// Picture maps the format settings of the picture.
    /// </summary>
    public struct Picture
    {
        public string Extension;
        public byte[]? File;
        public GraphicOptions? Format;
        public PictureInsertType InsertType;
    }

    /// <summary>
    /// RichTextRun directly maps the settings of the rich text run.
    /// </summary>
    public struct RichTextRun
    {
        public Font? Font;
        public string Text;
    }

    /// <summary>
    /// Comment directly maps the comment information.
    /// </summary>
    public struct Comment
    {
        public string Author;
        public int AuthorID;
        public string Cell;
        public string Text;
        public uint Width;
        public uint Height;
        public RichTextRun[]? Paragraph;
    }

    /// <summary>
    /// FormControl directly maps the form controls information.
    /// </summary>
    public struct FormControl
    {
        public string Cell;
        public string Macro;
        public uint Width;
        public uint Height;
        public bool Checked;
        public uint CurrentVal;
        public uint MinVal;
        public uint MaxVal;
        public uint IncChange;
        public uint PageChange;
        public bool Horizontally;
        public string CellLink;
        public string Text;
        public RichTextRun[]? Paragraph;
        public FormControlType Type;
        public GraphicOptions Format;
    }

    /// <summary>
    /// ChartNumFmt directly maps the number format settings of the chart.
    /// </summary>
    public struct ChartNumFmt
    {
        public string CustomNumFmt;
        public bool SourceLinked;
    }

    /// <summary>
    /// ChartAxis directly maps the format settings of the chart axis.
    /// </summary>
    public struct ChartAxis
    {
        public bool None;
        public bool DropLines;
        public bool HighLowLines;
        public bool MajorGridLines;
        public bool MinorGridLines;
        public double MajorUnit;
        public ChartDataLabelPositionType TickLabelPosition;
        public int TickLabelSkip;
        public bool ReverseOrder;
        public bool Secondary;
        public double? Maximum;
        public double? Minimum;
        public Alignment Alignment;
        public Font Font;
        public double LogBase;
        public ChartNumFmt NumFmt;
        public RichTextRun[]? Title;
    }

    /// <summary>
    /// ChartDataLabel directly maps the format settings of the chart labels.
    /// </summary>
    public struct ChartDataLabel
    {
        public Alignment Alignment;
        public Font Font;
        public Fill Fill;
    }

    /// <summary>
    /// ChartDimension directly maps the dimension of the chart.
    /// </summary>
    public struct ChartDimension
    {
        public uint Width;
        public uint Height;
    }

    /// <summary>
    /// ChartLine directly maps the format settings of the chart line.
    /// </summary>
    public struct ChartLine
    {
        public ChartLineType Type;
        public ChartDashType Dash;
        public Fill Fill;
        public bool Smooth;
        public double Width;
    }

    /// <summary>
    /// ChartUpDownBar directly maps the format settings of the stock chart up
    /// bars and down bars.
    /// </summary>
    public struct ChartUpDownBar
    {
        public Fill Fill;
        public ChartLine Border;
    }

    /// <summary>
    /// ChartPlotArea directly maps the format settings of the plot area.
    /// </summary>
    public struct ChartPlotArea
    {
        public int SecondPlotValues;
        public bool ShowBubbleSize;
        public bool ShowCatName;
        public bool ShowDataTable;
        public bool ShowDataTableKeys;
        public bool ShowLeaderLines;
        public bool ShowPercent;
        public bool ShowSerName;
        public bool ShowVal;
        public Fill Fill;
        public ChartUpDownBar UpBars;
        public ChartUpDownBar DownBars;
        public ChartNumFmt NumFmt;
    }

    /// <summary>
    /// ChartLegend directly maps the format settings of the chart legend.
    /// </summary>
    public struct ChartLegend
    {
        public string Position;
        public bool ShowLegendKey;
        public Font? Font;
    }

    /// <summary>
    /// ChartMarker directly maps the format settings of the chart marker.
    /// </summary>
    public struct ChartMarker
    {
        public ChartLine Border;
        public Fill Fill;
        public string Symbol;
        public int Size;
    }

    /// <summary>
    /// ChartDataPoint directly maps the format settings of the chart data point
    /// for doughnut, pie and 3D pie charts.
    /// </summary>
    public struct ChartDataPoint
    {
        public int Index;
        public Fill Fill;
    }

    /// <summary>
    /// ChartSeries directly maps the format settings of the chart series.
    /// </summary>
    public struct ChartSeries
    {
        public string Name;
        public string Categories;
        public string Values;
        public string Sizes;
        public Fill Fill;
        public ChartLegend Legend;
        public ChartLine Line;
        public ChartMarker Marker;
        public ChartDataLabel DataLabel;
        public ChartDataLabelPositionType DataLabelPosition;
        public ChartDataPoint[]? DataPoint;
    }

    /// <summary>
    /// Chart directly maps the format settings of the chart.
    /// </summary>
    public struct Chart
    {
        public ChartType Type;
        public ChartSeries[]? Series;
        public GraphicOptions Format;
        public ChartDimension Dimension;
        public ChartLegend Legend;
        public RichTextRun[]? Title;
        public bool? VaryColors;
        public ChartAxis XAxis;
        public ChartAxis YAxis;
        public ChartPlotArea PlotArea;
        public Fill Fill;
        public ChartLine Border;
        public string ShowBlanksAs;
        public int BubbleSize;
        public int HoleSize;
        public uint? GapWidth;
        public int? Overlap;
    }

    /// <summary>
    /// PivotTableField directly maps the field settings of the pivot table.
    /// </summary>
    /// <remarks>
    /// Name specifies the name of the data field. Maximum 255 characters
    /// are allowed in data field name, excess characters will be truncated.
    ///
    /// Subtotal specifies the aggregation function that applies to this data
    /// field. The default value is sum. The possible values for this attribute
    /// are:
    ///
    /// Average
    /// Count
    /// CountNums
    /// Max
    /// Min
    /// Product
    /// StdDev
    /// StdDevp
    /// Sum
    /// Var
    /// Varp
    ///
    /// NumFmt specifies the number format ID of the data field, this filed only
    /// accepts built-in number format ID and does not support custom number
    /// format expression currently.
    /// </remarks>
    public struct PivotTableField
    {
        public bool Compact;
        public string Data;
        public string Name;
        public bool Outline;
        public bool ShowAll;
        public bool InsertBlankRow;
        public string Subtotal;
        public bool DefaultSubtotal;
        public int NumFmt;
    }

    /// <summary>
    /// PivotTableOptions directly maps the format settings of the pivot table.
    /// </summary>
    /// <remarks>
    /// PivotTableStyleName: The built-in pivot table style names
    ///
    ///	PivotStyleLight1 - PivotStyleLight28
    ///	PivotStyleMedium1 - PivotStyleMedium28
    ///	PivotStyleDark1 - PivotStyleDark28
    /// </remarks>
    public struct PivotTableOptions
    {
        public string DataRange;
        public string PivotTableRange;
        public string Name;
        public PivotTableField[]? Rows;
        public PivotTableField[]? Columns;
        public PivotTableField[]? Data;
        public PivotTableField[]? Filter;
        public bool RowGrandTotals;
        public bool ColGrandTotals;
        public bool ShowDrill;
        public bool UseAutoFormatting;
        public bool PageOverThenDown;
        public bool MergeItem;
        public bool ClassicLayout;
        public bool CompactData;
        public bool ShowError;
        public bool ShowRowHeaders;
        public bool ShowColHeaders;
        public bool ShowRowStripes;
        public bool ShowColStripes;
        public bool ShowLastColumn;
        public bool FieldPrintTitles;
        public bool ItemPrintTitles;
        public string PivotTableStyleName;
    }

    /// <summary>
    /// ShapeLine directly maps the line settings of the shape.
    /// </summary>
    public struct ShapeLine
    {
        public string Color;
        public double? Width;
    }

    /// <summary>
    /// Shape directly maps the format settings of the shape.
    /// </summary>
    public struct Shape
    {
        public string Cell;
        public string Type;
        public string Macro;
        public uint Width;
        public uint Height;
        public GraphicOptions Format;
        public Fill Fill;
        public ShapeLine Line;
        public RichTextRun[]? Paragraph;
    }

    /// <summary>
    /// SheetPropsOptions provides a function to set worksheet properties.
    /// </summary>
    public struct SheetPropsOptions
    {
        public string? CodeName;
        public bool? EnableFormatConditionsCalculation;
        public bool? Published;
        public bool? AutoPageBreaks;
        public bool? FitToPage;
        public int? TabColorIndexed;
        public string? TabColorRGB;
        public int? TabColorTheme;
        public double? TabColorTint;
        public bool? OutlineSummaryBelow;
        public bool? OutlineSummaryRight;
        public uint? BaseColWidth;
        public double? DefaultColWidth;
        public double? DefaultRowHeight;
        public bool? CustomHeight;
        public bool? ZeroHeight;
        public bool? ThickTop;
        public bool? ThickBottom;
    }

    /// <summary>
    /// Represents the settings of the slicer.
    /// </summary>
    /// <remarks>
    /// <para><b>Name</b> specifies the slicer name and should be an existing
    /// field name of the given table or pivot table. This setting is
    /// required.</para>
    /// <para><b>Cell</b> specifies the top-left cell coordinates for inserting
    /// the slicer. This setting is required.</para>
    /// <para><b>TableSheet</b> specifies the worksheet name of the table or
    /// pivot table. This setting is required.</para>
    /// <para><b>TableName</b> specifies the name of the table or pivot table.
    /// This setting is required.</para>
    /// <para><b>Caption</b> specifies the caption of the slicer. This setting
    /// is optional.</para>
    /// <para><b>Macro</b> specifies the macro to assign to the slicer. The
    /// workbook extension should be XLSM or XLTM.</para>
    /// <para><b>Width</b> specifies the width of the slicer. This setting is
    /// optional.</para>
    /// <para><b>Height</b> specifies the height of the slicer. This setting is
    /// optional.</para>
    /// <para><b>DisplayHeader</b> specifies whether the slicer header is
    /// displayed. This setting is optional; the default is to display
    /// it.</para>
    /// <para><b>ItemDesc</b> specifies whether to sort items in descending
    /// (Z-A) order. This setting is optional; the default is false
    /// (ascending).</para>
    /// <para><b>Format</b> specifies the format of the slicer. This setting is
    /// optional.</para>
    /// </remarks>
    public struct SlicerOptions
    {
        public string Name;
        public string Cell;
        public string TableSheet;
        public string TableName;
        public string Caption;
        public string Macro;
        public uint Width;
        public uint Height;
        public bool? DisplayHeader;
        public bool ItemDesc;
        public GraphicOptions Format;
    }

    /// <summary>
    /// SparklineOptions directly maps the settings of the sparkline.
    /// </summary>
    public struct SparklineOptions
    {
        public string[]? Location;
        public string[]? Range;
        public int Max;
        public int CustMax;
        public int Min;
        public int CustMin;
        public string Type;
        public double Weight;
        public bool DateAxis;
        public bool Markers;
        public bool High;
        public bool Low;
        public bool First;
        public bool Last;
        public bool Negative;
        public bool Axis;
        public bool Hidden;
        public bool Reverse;
        public int Style;
        public string SeriesColor;
        public string NegativeColor;
        public string MarkersColor;
        public string FirstColor;
        public string LastColor;
        public string HightColor;
        public string LowColor;
        public string EmptyCells;
    }

    /// <summary>
    /// Table directly maps the format settings of the table.
    /// </summary>
    public struct Table
    {
        public string Range;
        public string Name;
        public string StyleName;
        public bool ShowColumnStripes;
        public bool ShowFirstColumn;
        public bool? ShowHeaderRow;
        public bool ShowLastColumn;
        public bool? ShowRowStripes;
    }

    /// <summary>
    /// ViewOptions directly maps the settings of sheet view.
    /// </summary>
    public struct ViewOptions
    {
        public bool? DefaultGridColor;
        public bool? RightToLeft;
        public bool? ShowFormulas;
        public bool? ShowGridLines;
        public bool? ShowRowColHeaders;
        public bool? ShowRuler;
        public bool? ShowZeros;
        public string? TopLeftCell;
        public string? View;
        public double? ZoomScale;
    }

    /// <summary>
    /// WorkbookPropsOptions directly maps the settings of workbook proprieties.
    /// </summary>
    public struct WorkbookPropsOptions
    {
        public bool? Date1904;
        public bool? FilterPrivacy;
        public string? CodeName;
    }

    public struct Cells
    {
        public string[]? Cell;
    }

    public struct StringMatrixErrorResult
    {
        public Cells[]? Row;
    }
}
