// Copyright 2025 - 2026 The excelize Authors. All rights reserved. Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.
//
// Package excelize-cs is a C# port of Go Excelize library, providing a set of
// functions that allow you to write and read from XLAM / XLSM / XLSX / XLTM /
// XLTX files. Supports reading and writing spreadsheet documents generated by
// Microsoft Excel™ 2007 and later. Supports complex components by high
// compatibility, and provided streaming API for generating or reading data from
// a worksheet with huge amounts of data. This library needs .NET version 6, C#
// version 10 or later.

using System.Runtime.InteropServices;

namespace ExcelizeCs.TypesC
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Interface
    {
        public int Type;
        public int Integer;
        public int Integer32;
        public sbyte* String;
        public double Float;

        [MarshalAs(UnmanagedType.I1)]
        public bool Boolean;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Options
    {
        public uint MaxCalcIterations;
        public sbyte* Password;

        [MarshalAs(UnmanagedType.I1)]
        public bool RawCellValue;
        public long UnzipSizeLimit;
        public long UnzipXMLSizeLimit;
        public sbyte* TmpDir;
        public sbyte* ShortDatePattern;
        public sbyte* LongDatePattern;
        public sbyte* LongTimePattern;
        public byte CultureInfo;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct AppProperties
    {
        public sbyte* Application;

        [MarshalAs(UnmanagedType.I1)]
        public bool ScaleCrop;
        public int DocSecurity;
        public sbyte* Company;

        [MarshalAs(UnmanagedType.I1)]
        public bool LinksUpToDate;

        [MarshalAs(UnmanagedType.I1)]
        public bool HyperlinksChanged;
        public sbyte* AppVersion;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct CalcPropsOptions
    {
        public uint* CalcID;
        public sbyte** CalcMode;
        public bool* FullCalcOnLoad;
        public sbyte** RefMode;
        public bool* Iterate;
        public uint* IterateCount;
        public float* IterateDelta;
        public bool* FullPrecision;
        public bool* CalcCompleted;
        public bool* CalcOnSave;
        public bool* ConcurrentCalc;
        public uint* ConcurrentManualCount;
        public bool* ForceFullCalc;
    };

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Border
    {
        public sbyte* Type;
        public sbyte* Color;
        public int Style;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Fill
    {
        public sbyte* Type;
        public int Pattern;
        public int ColorLen;
        public sbyte** Color;
        public int Shading;
        public int Transparency;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Font
    {
        [MarshalAs(UnmanagedType.I1)]
        public bool Bold;

        [MarshalAs(UnmanagedType.I1)]
        public bool Italic;

        public sbyte* Underline;
        public sbyte* Family;
        public double Size;

        [MarshalAs(UnmanagedType.I1)]
        public bool Strike;

        public sbyte* Color;
        public int ColorIndexed;
        public int* ColorTheme;
        public double ColorTint;
        public sbyte* VertAlign;
        public int* Charset;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Alignment
    {
        public sbyte* Horizontal;
        public int Indent;

        [MarshalAs(UnmanagedType.I1)]
        public bool JustifyLastLine;

        public uint ReadingOrder;
        public int RelativeIndent;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShrinkToFit;

        public int TextRotation;
        public sbyte* Vertical;

        [MarshalAs(UnmanagedType.I1)]
        public bool WrapText;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct Protection
    {
        [MarshalAs(UnmanagedType.I1)]
        public bool Hidden;

        [MarshalAs(UnmanagedType.I1)]
        public bool Locked;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct AutoFilterOptions
    {
        public sbyte* Column;
        public sbyte* Expression;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct FormulaOpts
    {
        public sbyte** Type;
        public sbyte** Ref;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct HeaderFooterOptions
    {
        public bool* AlignWithMargins;

        [MarshalAs(UnmanagedType.I1)]
        public bool DifferentFirst;

        [MarshalAs(UnmanagedType.I1)]
        public bool DifferentOddEven;
        public bool* ScaleWithDoc;
        public sbyte* OddHeader;
        public sbyte* OddFooter;
        public sbyte* EvenHeader;
        public sbyte* EvenFooter;
        public sbyte* FirstHeader;
        public sbyte* FirstFooter;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct HeaderFooterImageOptions
    {
        public byte Position;
        public int FileLen;
        public byte* File;

        [MarshalAs(UnmanagedType.I1)]
        public bool IsFooter;

        [MarshalAs(UnmanagedType.I1)]
        public bool FirstPage;
        public sbyte* Extension;
        public sbyte* Width;
        public sbyte* Height;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct HyperlinkOpts
    {
        public sbyte** Display;
        public sbyte** Tooltip;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Style
    {
        public int BorderLen;
        public Border* Border;
        public Fill Fill;
        public Font* Font;
        public Alignment* Alignment;
        public Protection* Protection;
        public int NumFmt;
        public int* DecimalPlaces;
        public sbyte** CustomNumFmt;

        [MarshalAs(UnmanagedType.I1)]
        public bool NegRed;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GraphicOptions
    {
        public sbyte* AltText;
        public sbyte* Name;
        public bool* PrintObject;
        public bool* Locked;

        [MarshalAs(UnmanagedType.I1)]
        public bool LockAspectRatio;

        [MarshalAs(UnmanagedType.I1)]
        public bool AutoFit;

        [MarshalAs(UnmanagedType.I1)]
        public bool AutoFitIgnoreAspect;
        public int OffsetX;
        public int OffsetY;
        public double ScaleX;
        public double ScaleY;
        public sbyte* Hyperlink;
        public sbyte* HyperlinkType;
        public sbyte* Positioning;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Picture
    {
        public sbyte* Extension;
        public int FileLen;
        public byte* File;
        public GraphicOptions* Format;
        public byte InsertType;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct RichTextRun
    {
        public Font* Font;
        public sbyte* Text;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Comment
    {
        public sbyte* Author;
        public int AuthorID;
        public sbyte* Cell;
        public sbyte* Text;
        public uint Width;
        public uint Height;
        public int ParagraphLen;
        public RichTextRun* Paragraph;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ConditionalFormatOptions
    {
        public sbyte* Type;

        [MarshalAs(UnmanagedType.I1)]
        public bool AboveAverage;

        [MarshalAs(UnmanagedType.I1)]
        public bool Percent;
        public int* Format;
        public sbyte* Criteria;
        public sbyte* Value;
        public sbyte* MinType;
        public sbyte* MidType;
        public sbyte* MaxType;
        public sbyte* MinValue;
        public sbyte* MidValue;
        public sbyte* MaxValue;
        public sbyte* MinColor;
        public sbyte* MidColor;
        public sbyte* MaxColor;
        public sbyte* BarColor;
        public sbyte* BarBorderColor;
        public sbyte* BarDirection;

        [MarshalAs(UnmanagedType.I1)]
        public bool BarOnly;

        [MarshalAs(UnmanagedType.I1)]
        public bool BarSolid;
        public sbyte* IconStyle;

        [MarshalAs(UnmanagedType.I1)]
        public bool ReverseIcons;

        [MarshalAs(UnmanagedType.I1)]
        public bool IconsOnly;

        [MarshalAs(UnmanagedType.I1)]
        public bool StopIfTrue;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct FormControl
    {
        public sbyte* Cell;
        public sbyte* Macro;
        public uint Width;
        public uint Height;

        [MarshalAs(UnmanagedType.I1)]
        public bool Checked;
        public uint CurrentVal;
        public uint MinVal;
        public uint MaxVal;
        public uint IncChange;
        public uint PageChange;

        [MarshalAs(UnmanagedType.I1)]
        public bool Horizontally;
        public sbyte* CellLink;
        public sbyte* Text;
        public int ParagraphLen;
        public RichTextRun* Paragraph;
        public uint Type;
        public GraphicOptions Format;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ChartNumFmt
    {
        public sbyte* CustomNumFmt;

        [MarshalAs(UnmanagedType.I1)]
        public bool SourceLinked;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ChartAxis
    {
        [MarshalAs(UnmanagedType.I1)]
        public bool None;

        [MarshalAs(UnmanagedType.I1)]
        public bool DropLines;

        [MarshalAs(UnmanagedType.I1)]
        public bool HighLowLines;

        [MarshalAs(UnmanagedType.I1)]
        public bool MajorGridLines;

        [MarshalAs(UnmanagedType.I1)]
        public bool MinorGridLines;
        public double MajorUnit;
        public byte TickLabelPosition;
        public int TickLabelSkip;

        [MarshalAs(UnmanagedType.I1)]
        public bool ReverseOrder;

        [MarshalAs(UnmanagedType.I1)]
        public bool Secondary;
        public double* Maximum;
        public double* Minimum;
        public Alignment Alignment;
        public Font Font;
        public double LogBase;
        public ChartNumFmt NumFmt;
        public int TitleLen;
        public RichTextRun* Title;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct ChartDataLabel
    {
        public Alignment Alignment;
        public Font Font;
        public Fill Fill;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct ChartDimension
    {
        public uint Width;
        public uint Height;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct ChartLine
    {
        public byte Type;
        public byte Dash;
        public Fill Fill;

        [MarshalAs(UnmanagedType.I1)]
        public bool Smooth;
        public double Width;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ChartUpDownBar
    {
        public Fill Fill;
        public ChartLine Border;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct ChartPlotArea
    {
        public int SecondPlotValues;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowBubbleSize;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowCatName;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowDataTable;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowDataTableKeys;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowLeaderLines;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowPercent;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowSerName;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowVal;
        public Fill Fill;
        public ChartUpDownBar UpBars;
        public ChartUpDownBar DownBars;
        public ChartNumFmt NumFmt;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ChartLegend
    {
        public sbyte* Position;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowLegendKey;
        public Font* Font;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ChartMarker
    {
        public ChartLine Border;
        public Fill Fill;
        public sbyte* Symbol;
        public int Size;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct ChartDataPoint
    {
        public int Index;
        public Fill Fill;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ChartSeries
    {
        public sbyte* Name;
        public sbyte* Categories;
        public sbyte* Values;
        public sbyte* Sizes;
        public Fill Fill;
        public ChartLegend Legend;
        public ChartLine Line;
        public ChartMarker Marker;
        public ChartDataLabel DataLabel;
        public byte DataLabelPosition;
        public int DataPointLen;
        public ChartDataPoint* DataPoint;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Chart
    {
        public byte Type;
        public int SeriesLen;
        public ChartSeries* Series;
        public GraphicOptions Format;
        public ChartDimension Dimension;
        public ChartLegend Legend;
        public int TitleLen;
        public RichTextRun* Title;

        public bool* VaryColors;
        public ChartAxis XAxis;
        public ChartAxis YAxis;
        public ChartPlotArea PlotArea;
        public Fill Fill;
        public ChartLine Border;
        public sbyte* ShowBlanksAs;
        public int BubbleSize;
        public int HoleSize;
        public uint* GapWidth;
        public int* Overlap;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct PivotTableField
    {
        [MarshalAs(UnmanagedType.I1)]
        public bool Compact;
        public sbyte* Data;
        public sbyte* Name;

        [MarshalAs(UnmanagedType.I1)]
        public bool Outline;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowAll;

        [MarshalAs(UnmanagedType.I1)]
        public bool InsertBlankRow;
        public sbyte* Subtotal;

        [MarshalAs(UnmanagedType.I1)]
        public bool DefaultSubtotal;
        public int NumFmt;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct PivotTableOptions
    {
        public sbyte* DataRange;
        public sbyte* PivotTableRange;
        public sbyte* Name;
        public int RowsLen;
        public PivotTableField* Rows;
        public int ColumnsLen;
        public PivotTableField* Columns;
        public int DataLen;
        public PivotTableField* Data;
        public int FilterLen;
        public PivotTableField* Filter;

        [MarshalAs(UnmanagedType.I1)]
        public bool RowGrandTotals;

        [MarshalAs(UnmanagedType.I1)]
        public bool ColGrandTotals;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowDrill;

        [MarshalAs(UnmanagedType.I1)]
        public bool UseAutoFormatting;

        [MarshalAs(UnmanagedType.I1)]
        public bool PageOverThenDown;

        [MarshalAs(UnmanagedType.I1)]
        public bool MergeItem;

        [MarshalAs(UnmanagedType.I1)]
        public bool ClassicLayout;

        [MarshalAs(UnmanagedType.I1)]
        public bool CompactData;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowError;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowRowHeaders;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowColHeaders;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowRowStripes;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowColStripes;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowLastColumn;

        [MarshalAs(UnmanagedType.I1)]
        public bool FieldPrintTitles;

        [MarshalAs(UnmanagedType.I1)]
        public bool ItemPrintTitles;
        public sbyte* PivotTableStyleName;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ShapeLine
    {
        public sbyte* Color;
        public double* Width;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Shape
    {
        public sbyte* Cell;
        public sbyte* Type;
        public sbyte* Macro;
        public uint Width;
        public uint Height;
        public GraphicOptions Format;
        public Fill Fill;
        public ShapeLine Line;
        public int ParagraphLen;
        public RichTextRun* Paragraph;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct SheetPropsOptions
    {
        public sbyte** CodeName;
        public bool* EnableFormatConditionsCalculation;
        public bool* Published;
        public bool* AutoPageBreaks;
        public bool* FitToPage;
        public int* TabColorIndexed;
        public sbyte** TabColorRGB;
        public int* TabColorTheme;
        public double* TabColorTint;
        public bool* OutlineSummaryBelow;
        public bool* OutlineSummaryRight;
        public uint* BaseColWidth;
        public double* DefaultColWidth;
        public double* DefaultRowHeight;
        public bool* CustomHeight;
        public bool* ZeroHeight;
        public bool* ThickTop;
        public bool* ThickBottom;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct SlicerOptions
    {
        public sbyte* Name;
        public sbyte* Cell;
        public sbyte* TableSheet;
        public sbyte* TableName;
        public sbyte* Caption;
        public sbyte* Macro;
        public uint Width;
        public uint Height;
        public bool* DisplayHeader;

        [MarshalAs(UnmanagedType.I1)]
        public bool ItemDesc;
        public GraphicOptions Format;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct SparklineOptions
    {
        public int LocationLen;
        public sbyte** Location;
        public int RangeLen;
        public sbyte** Range;
        public int Max;
        public int CustMax;
        public int Min;
        public int CustMin;
        public sbyte* Type;
        public double Weight;

        [MarshalAs(UnmanagedType.I1)]
        public bool DateAxis;

        [MarshalAs(UnmanagedType.I1)]
        public bool Markers;

        [MarshalAs(UnmanagedType.I1)]
        public bool High;

        [MarshalAs(UnmanagedType.I1)]
        public bool Low;

        [MarshalAs(UnmanagedType.I1)]
        public bool First;

        [MarshalAs(UnmanagedType.I1)]
        public bool Last;

        [MarshalAs(UnmanagedType.I1)]
        public bool Negative;

        [MarshalAs(UnmanagedType.I1)]
        public bool Axis;

        [MarshalAs(UnmanagedType.I1)]
        public bool Hidden;

        [MarshalAs(UnmanagedType.I1)]
        public bool Reverse;
        public int Style;
        public sbyte* SeriesColor;
        public sbyte* NegativeColor;
        public sbyte* MarkersColor;
        public sbyte* FirstColor;
        public sbyte* LastColor;
        public sbyte* HightColor;
        public sbyte* LowColor;
        public sbyte* EmptyCells;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Table
    {
        public sbyte* Range;
        public sbyte* Name;
        public sbyte* StyleName;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowColumnStripes;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowFirstColumn;
        public bool* ShowHeaderRow;

        [MarshalAs(UnmanagedType.I1)]
        public bool ShowLastColumn;
        public bool* ShowRowStripes;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct ViewOptions
    {
        public bool* DefaultGridColor;
        public bool* RightToLeft;
        public bool* ShowFormulas;
        public bool* ShowGridLines;
        public bool* ShowRowColHeaders;
        public bool* ShowRuler;
        public bool* ShowZeros;
        public sbyte** TopLeftCell;
        public sbyte** View;
        public double* ZoomScale;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WorkbookPropsOptions
    {
        public bool* Date1904;
        public bool* FilterPrivacy;
        public sbyte** CodeName;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct StringErrorResult
    {
        public sbyte* val;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct StringIntErrorResult
    {
        public sbyte* strVal;
        public int intVal;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct IntErrorResult
    {
        public int val;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct CellNameToCoordinatesResult
    {
        public int col;
        public int row;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GetAppPropsResult
    {
        public AppProperties opts;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GetCalcPropsResult
    {
        public CalcPropsOptions opts;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct Cells
    {
        public int CellLen;
        public sbyte** Cell;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct StringMatrixErrorResult
    {
        public int RowLen;
        public Cells* Row;
        public sbyte* err;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct GetStyleResult
    {
        public Style style;
        public sbyte* err;
    }
}
